import type { NextPage } from "next";
import Advantage1 from "./advantage1";
import Advantage from "./advantage";
import styles from "./our-mission.module.css";

const OurMission: NextPage = () => {
  return (
    <section className={styles.ourMission}>
      <img className={styles.imageIcon} alt="" src="/image.svg" />
      <div className={styles.benefitsGrid}>
        <Advantage1 />
        <div className={styles.advantage}>
          <div className={styles.frameParent}>
            <div className={styles.profitabilityAndGrowthParent}>
              <b
                className={styles.profitabilityAndGrowth}
              >{`Transparent & Fair Decentralized Earnings`}</b>
              <img
                className={styles.frameChild}
                alt=""
                src="/frame-145-1.svg"
              />
              <img className={styles.icon} alt="" src="/icon-1@2x.png" />
            </div>
            <div className={styles.atCreonWeDeliverAUniqueWrapper}>
              <div className={styles.atCreonWe}>
                The key element of our proposal is the continuous access to
                distributed and decentralized earnings generated by AI tools
                that we provide through their creation or investment in them.
                This decentralized structure ensures greater transparency and
                fairness to all participants in the Creon ecosystem.
              </div>
            </div>
          </div>
        </div>
        <Advantage
          launchingThe="Launching the"
          future="future"
          icon="/icon-2@2x.png"
          atCreonWeDeliverAUniqueOp="What's more, Creon is pioneering in offering the first known opportunity to acquire allocations in tokenised AI projects through our Creon Launchpad platform. This gives investors a unique chance for early engagement in the most promising AI projects, opening the door to potentially high returns."
        />
        <Advantage
          launchingThe="Limitless Possibilities of AI"
          future={`& Crypto`}
          icon="/icon-3@2x.png"
          atCreonWeDeliverAUniqueOp="The possibilities offered by the integration of AI and cryptocurrencies are limitless, and we're just beginning to explore them. As pioneers, our journey into uncharted territory is fraught with challenges, but the rewards promise to be equally extraordinary. Creon isn’t just about profiting from technological innovation; it's about being part of the process that brings these innovations to life."
        />
      </div>
      <h1 className={styles.ourVisionIsContainer}>
        <span>{`Our vision is to support the innovation of AI blockchain projects `}</span>
        <span className={styles.whilePrioritizingCommunities}>
          while prioritizing communities and democratizing profits
        </span>
      </h1>
    </section>
  );
};

export default OurMission;
